[package]
name = "sine_synth"
version = "0.1.0"
authors = ["Rob Saunders <hello@robsaunders.io>"]

[dependencies]
vst2 = { git = "https://github.com/overdrivenpotato/rust-vst2" }
sdl2 = "0.30.0"
libc = "*"

[lib]
name = "sine_synth"
crate-type = ["cdylib"]
